# Generated by Django 5.1.2 on 2025-06-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('prize', models.PositiveSmallIntegerField()),
                ('stock', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
