# Generated by Django 5.1.2 on 2025-06-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['categ', 'name']},
        ),
        migrations.AddField(
            model_name='item',
            name='categ',
            field=models.CharField(choices=[('B', 'Bebida'), ('C', 'Comida'), ('M', 'Miscelaneo')], default='S', max_length=10),
        ),
    ]
