# Generated by Django 5.1.2 on 2025-06-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carta', '0002_alter_item_options_item_categ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='categ',
            field=models.CharField(choices=[('B', 'Bebida'), ('C', 'Comida'), ('M', 'Miscelaneo')], default='B', max_length=10),
        ),
    ]
